version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment: 
      POSTGRES_USER: $POSTGRES_USER 
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      DATABASE_URL: $DATABASE_URL