version: "3"
services:
  api:
    image: "marycode/nestjs-travel-api"
    mem_limit: 128m
    hostname: api
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
