version: "3"
services:
  server:
    image: "marycode/nestjs-travel-api-api"
    mem_limit: 128m
    hostname: api
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - DATABASE_URL=$DATABASE_URL
  nginx:
    image: "marycode/nestjs-travel-api-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"